server:
  port: 8888
  servlet:
    context-path: /develop

---

spring:
  data:
    mongodb:
      host: 38.6.174.40
      port: 40017
      database: ydoest
      username: admin
      password: 123456
      authentication-database: admin