server:
  port: 8888
  servlet:
    context-path: /develop
  undertow:
    buffer-size: 1048576      # 单位 byte
    direct-buffers: true
    threads:
      worker: 10

---

spring:
  data:
    mongodb:
      host: 38.6.174.40
      port: 40017
      database: ydoest
      username: admin
      password: 123456
      authentication-database: admin
  datasource:
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5

---

logging:
  charset:
    console: utf-8
